# Generated by Django 2.2 on 2020-11-08 21:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('published', models.BooleanField(default=True, verbose_name='Published on')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('blog_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Blog Title')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('blog_short_description', models.TextField()),
                ('blog_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_published_date', models.DateTimeField()),
                ('blog_author', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Blog Author')),
                ('search_friendly', models.TextField(blank=True, null=True, verbose_name='Search Friendly')),
                ('featured', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('blog_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_category', to='blog.BlogCategory', verbose_name='Blog Category')),
                ('blog_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_image', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': ' Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
