# Generated by Django 2.2 on 2020-11-10 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=100, verbose_name='Email')),
                ('hash', models.TextField()),
                ('notification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Notification')),
                ('subscribed', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Email Subscriptions',
            },
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blog_category',
        ),
        migrations.CreateModel(
            name='BlogTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('topic', models.CharField(max_length=100, verbose_name='Topic')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('published', models.BooleanField(default=True, verbose_name='Published on')),
                ('blog_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_category', to='blog.BlogCategory', verbose_name='Blog Category')),
            ],
            options={
                'verbose_name': 'Blog Topic',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_topic', to='blog.BlogTopic', verbose_name='Blog Category'),
        ),
    ]
