# Generated by Django 2.2 on 2020-11-10 11:05

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('blog', '0002_auto_20201110_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtopic',
            options={'verbose_name': 'Blog Topic', 'verbose_name_plural': 'Blog Topics'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_big_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_big_image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
